version: 2.1

orbs:
  maven: circleci/maven@0.0.12

executors:
  docker:
    - image: cimg/openjdk:13.0

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results

