version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: kEt#uR6M
  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080
