apiVersion: v1
kind: Service
metadata:
    name: postgres-service
    namespace: microservice-catalog
    labels:
        app: microservice-catalog
        tier: service
spec:
    ports:
        -   name: postgres
            port: 5432
            targetPort: 5432
            protocol: TCP
    selector:
        app: microservice-catalog
        tier: database

---
apiVersion: v1
kind: Service
metadata:
    name: microservice-catalog-service
    namespace: microservice-catalog
    labels:
        app: microservice-catalog
        tier: service
spec:
    ports:
        -   name: microservice-catalog
            port: 8081
            targetPort: 8081
            protocol: TCP
    type: LoadBalancer
    selector:
        app: microservice-catalog
        tier: business
