apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-pv-claim
    namespace: microservice-catalog
    labels:
        app: microservice-catalog
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 50M
